# Generated by Django 2.0.6 on 2018-09-23 15:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(max_length=3)),
                ('header', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 9, 23, 15, 42, 26, 569671))),
                ('updated', models.DateTimeField(default=datetime.datetime(2018, 9, 23, 15, 42, 26, 569700))),
                ('header', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('private', models.BooleanField(default=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duck.Calendar')),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='duck.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(default=5)),
                ('duration', models.IntegerField(default=30)),
                ('due', models.DateTimeField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duck.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('timezone', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='invite',
            name='invitee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='duck.Profile'),
        ),
        migrations.AddField(
            model_name='invite',
            name='organizer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='duck.Profile'),
        ),
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end', to='duck.Time'),
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='start', to='duck.Time'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duck.Profile'),
        ),
    ]
