# Generated by Django 2.0.6 on 2018-10-08 15:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('duck', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='people',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start',
        ),
        migrations.AddField(
            model_name='event',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='endtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='startdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='starttime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='timezone',
            field=models.CharField(default='EST', max_length=3),
        ),
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 8, 15, 34, 58, 464792, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 8, 15, 34, 58, 464824, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.IntegerField(blank=True, default=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
