# Generated by Django 2.0.6 on 2018-10-08 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('duck', '0002_auto_20181008_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
