# Generated by Django 2.0.6 on 2018-10-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duck', '0003_auto_20181008_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='startdate',
        ),
        migrations.RemoveField(
            model_name='event',
            name='starttime',
        ),
        migrations.AddField(
            model_name='event',
            name='startTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='endtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
