# Generated by Django 2.0.6 on 2018-10-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duck', '0004_auto_20181008_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='googleID',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='googleID',
            field=models.TextField(blank=True, null=True),
        ),
    ]
