# Generated by Django 2.0.6 on 2018-10-15 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duck', '0005_auto_20181012_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='endtime',
            new_name='endTime',
        ),
    ]
