# Generated by Django 2.0.6 on 2018-10-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duck', '0006_auto_20181015_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timezone',
            field=models.CharField(default='EST', max_length=100),
        ),
    ]
