# Generated by Django 2.0.6 on 2018-11-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duck', '0006_auto_20181108_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='recurring',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
